Feature/7 training screen
LaZona16/zone_app pull request #7
Opened 2022-08-10 01:09 UTC by BrayanRGarciaM

2022-08-10 15:51 UTC, juliomejia97 requested changes
Awesome job! Really good job. Please review the changes. Also, run flutter `flutter analyze` in order to lint the code created

2022-08-10 15:51 UTC, juliomejia97 commented on .flutter-plugins-dependencies
> +{"info":"This is a generated file; do not edit or check into version control.","plugins":{"ios":[{"name":"flutter_blue_plus","path":"C:\\\\Users\\\\ASUS\\\\Desktop\\\\LaZona\\\\flutter\\\\.pub-cache\
Please, review this file because is not necessary to be added

2022-08-10 15:51 UTC, juliomejia97 commented on lib/main.dart
>  }
Create a separate file in core.

2022-08-10 15:51 UTC, juliomejia97 commented on lib/src/features/devices/presentation/training/statistic/pass/overall_pass.dart
> +    ]);
Please add format and make more bigger the text

2022-08-10 15:51 UTC, juliomejia97 commented on lib/src/features/devices/presentation/training/statistic/pass/overall_pass.dart
> +      Text(widget.titleCategory,
```suggestion
     const Text(widget.titleCategory,
```

2022-08-10 15:51 UTC, juliomejia97 commented on lib/src/features/devices/presentation/training/statistic/precision/wall_statistic.dart
> +        height: MediaQuery.of(context).size.height * 0.1,
Please, make it a little beat less high
```suggestion
        height: MediaQuery.of(context).size.height * 0.09,
```

2022-08-10 15:51 UTC, juliomejia97 commented on lib/src/features/devices/presentation/training/statistic/precision/precision.dart
> +      margin: const EdgeInsets.only(left: 20, right: 10, top: 10),
Please, make it more center the wall. Maybe reduce the left.

2022-08-10 15:51 UTC, juliomejia97 commented on lib/src/features/devices/presentation/training/statistic/statistics.dart
> +              children: ForceConsistency())
🤩

2022-08-10 15:51 UTC, juliomejia97 commented on lib/src/features/devices/presentation/training/statistic/statistics.dart
> +class StatisticCard extends StatelessWidget {
Please, move this to another widget

2022-08-10 15:51 UTC, juliomejia97 commented on lib/src/features/devices/presentation/training/statistic/time_per_touch/time_per_touch.dart
> +class TimePerTouch extends StatefulWidget {
👍 Brutal!

2022-08-10 15:51 UTC, juliomejia97 commented on lib/src/features/devices/presentation/training/training_screen.dart
> +  }
Good idea!

2022-08-10 15:51 UTC, juliomejia97 commented on lib/src/features/devices/presentation/training/wall_control.dart
> +}
This has to be rendered according the number of walls selected. In the mid time create a variable and build this according the variable. With a .map or a .for you can perform this

2022-08-17 03:24 UTC, BrayanRGarciaM commented on lib/src/features/devices/presentation/training/statistic/pass/overall_pass.dart
> +      Text(widget.titleCategory,
When we use a non const variable like widget.titleCategor, we can not put const

2022-08-18 04:25 UTC, juliomejia97 requested changes
Again, please before push run `flutter analyze` to make sure the checks are gonna pass

2022-08-18 04:25 UTC, juliomejia97 commented on .flutter-plugins-dependencies
> +{"info":"This is a generated file; do not edit or check into version control.","plugins":{"ios":[{"name":"flutter_blue_plus","path":"C:\\\\Users\\\\ASUS\\\\Desktop\\\\LaZona\\\\flutter\\\\.pub-cache\
Remove this file from commits history

2022-08-18 04:25 UTC, juliomejia97 commented on lib/src/features/devices/presentation/training/statistic/precision/precision.dart
> +      margin: const EdgeInsets.all(20),
Review this value, maybe reduce to 10

2022-08-18 04:25 UTC, juliomejia97 commented on lib/src/features/devices/presentation/training/training_screen.dart
> +      body: Column(children: [const BuildTime(), const WallSetting(), Statistic()]),
Format

2022-08-18 04:27 UTC, juliomejia97 commented on lib/src/core/strings.dart
> +const String MANUAL_CONTROL = "Manual Control";
// ignore_for_file: constant_identifier_names insert this line before

2022-08-19 02:28 UTC, juliomejia97 approved these changes

2022-08-19 02:36 UTC, leonardomn12 approved these changes

2022-08-19 02:45 UTC, merged