Feature/53 Add Timer Functionality
LaZona16/zone_app pull request #8
Opened 2022-08-28 22:34 UTC by juliomejia97

This functionality implements a timer using bloc pattern.
User can:
- Init the timer
- Run Timer
- Pause Timer
- Reset Timer
- Re-run Timer
Demo:

https://user-images.githubusercontent.com/19478156/187097273-fb8c4333-f4ef-4b88-9297-8609e266b48f.mp4

2022-08-29 23:27 UTC, leonardomn12 approved these changes

2022-08-30 02:42 UTC, BrayanRGarciaM requested changes
Pretty good, I added some little comments

2022-08-30 02:42 UTC, BrayanRGarciaM commented on lib/src/features/devices/data/repository/timer_repository_impl.dart
> +        Stream.periodic(const Duration(seconds: 1), (x) => ticks - x - 1)
Put the number in a Variable. Because I don't know what is 1
It could be (?)
```suggestion
        Stream.periodic(const Duration(seconds: FIRST_SECOND), (x) => ticks - x - FIRST_SECOND)
```

2022-08-30 02:42 UTC, BrayanRGarciaM commented on lib/src/features/devices/presentation/bloc/timer/timer_cubit.dart
> +      duration > 0
```suggestion
      duration > END_DURATION
```

2022-08-30 02:42 UTC, BrayanRGarciaM commented on lib/src/features/devices/presentation/bloc/timer/timer_state.dart
> +        selectedTime = DateTime(DateTime.now().year),
Why year?

2022-08-30 02:42 UTC, BrayanRGarciaM commented on lib/src/features/devices/presentation/training/build_time.dart
> +      value: sl<TimerCubit>(),
Nice

2022-08-30 04:47 UTC, juliomejia97 commented on lib/src/features/devices/presentation/bloc/timer/timer_state.dart
> +        selectedTime = DateTime(DateTime.now().year),
The year is the current. So it will use the run time year.

2022-08-30 04:52 UTC, juliomejia97 commented on lib/src/features/devices/data/repository/timer_repository_impl.dart
> +        Stream.periodic(const Duration(seconds: 1), (x) => ticks - x - 1)
I don't see it as useful. The stream is running the internal formula each second

2022-08-30 04:55 UTC, juliomejia97 commented on lib/src/features/devices/presentation/bloc/timer/timer_cubit.dart
> +      duration > 0
I don't see useful the use case will be always the same. The end will be always the moment 0

2022-09-02 00:01 UTC, leonardomn12 approved these changes

2022-09-02 01:23 UTC, BrayanRGarciaM approved these changes

2022-09-02 01:24 UTC, BrayanRGarciaM submitted a review, later dismissed

2022-09-02 02:24 UTC, leonardomn12 approved these changes

2022-09-02 02:25 UTC, LaZona16 approved these changes

2022-09-02 02:34 UTC, merged